### ISSUE TITLE
Use PICASSO in python script

### ISSUE THREAD

**Issue by JLiLab** [nygctech/PICASSO#2]
Hi, 

Thank you for sharing the script. The plugin works very well in the interactive mode. I want to use the method to bath-process images. I am a novice in python. I wonder if you can share a snippet on how to use the plugin in python script.

Thank you in advance, 

James

**Comment by JLiLab** [comment]
I got to this far in writing python codes: 

from picasso import nn_picasso
import matplotlib.pyplot as plt
import imageio
import numpy as np

mixed = imageio.mimread(‘mouse_spinalcord_small.tiff’)
mixed = np.stack(mixed)

mixing_matrix = np.array([1, -1, 0, 0])
picasso = nn_picasso.PICASSOnn(mixing_matrix, mi_weight = 0.9)

train_info = picasso.train_loop(mixed, batch_size = 10000, max_iter=100, lr = 1e-3)
unmixed = picasso.unmix_images(mixed)

But I got this error: 
“AttributeError: ‘PICASSOnn’ object has no attribute ‘dask_collate’”. 

Any suggestion on how to fix it?

**Comment by krpandit** [comment]
I usually unmix the images using the model ```sink_image = (source_image - picasso_background)  * picasso_alpha ``` so I can customize the how memory managed.

But the unmix_images function should work, so I'll take a look at it.

**Comment by krpandit** [comment]
I fixed unmix_images() in #3. 

I also added an unmixing example notebook in the notebook directory

Currently trying to figure out why some tests are not passing.

**Comment by krpandit** [comment]
All tests passed locally, but not on github.

I'm going to close this issue and try to fix tests on github separately.

**Comment by psobolewskiPhD** [comment]
Thanks for fixing this @krpandit
I made a PR to try and fix tests 😊

**Comment by JLiLab** [comment]
Thank you, @krpandit. 

The second part for unmoving worked but model.unmix_images gave errors:

# Unmix images by batching on GPU
unmixed_sink = model.unmix_images([sink_im, source_im])

ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_1556\2154355721.py in <module>
      1 mixing_matrix = np.array([[1],[-1]])
      2 model = PICASSOnn(mixing_matrix)
----> 3 unmixed_sink = model.unmix_images([sink_im, source_im])
      4 
      5 

~\miniconda3\envs\napari\lib\site-packages\picasso\nn_picasso.py in unmix_images(self, images, batch_size)
    323         px, n_ims = unmixed.shape
    324         for i in range(n_ims):
--> 325             im = unmixed[:,i].reshape(dataset.rows,dataset.cols)
    326             unmixed_.append((im*dataset.max_px).astype(dataset.dtype))
    327 

~\miniconda3\envs\napari\lib\site-packages\dask\array\core.py in reshape(self, merge_chunks, limit, *shape)
   2185         if len(shape) == 1 and not isinstance(shape[0], Number):
   2186             shape = shape[0]
-> 2187         return reshape(self, shape, merge_chunks=merge_chunks, limit=limit)
   2188 
   2189     def topk(self, k, axis=-1, split_every=None):

~\miniconda3\envs\napari\lib\site-packages\dask\array\reshape.py in reshape(x, shape, merge_chunks, limit)
    224 
    225     if reduce(mul, shape, 1) != x.size:
--> 226         raise ValueError("total size of new array must be unchanged")
    227 
    228     if x.shape == shape:

ValueError: total size of new array must be unchangedpip install git+https://github.com/nygctech/PICASSO

**Comment by krpandit** [comment]
Is this the output from the unmixing_example.ipynb or a python script? If it's from a script can you post the script?

I think you're missing a model optimization step after you make the model and before you unmix it.

```
# Optimize model
for i in model.train_loop([sink_im, source_im]):
    pass
```

Also, what is the sink_im and source_im used?

**Comment by JLiLab** [comment]
My mistake. You are right @krpandit.
In the meantime, I noticed that algorithm seems to stop working when the image increases to a certain size. When I tested a 15,000 x 5,700 (750MB) image, unmixing worked only when I resized the image to around 50%. Does this make sense to you?

**Comment by krpandit** [comment]
The optimization and unmixing are going to scale with the image size. I tried to manage the memory by breaking up the images into smaller chunks that will fit into the system memory. If your system doesn't have a bunch of RAM it's going to break up the images into a lot more chunks and loop through each chunk for each iteration of the optimization loop. Same with unmix_images().

So I would expect the algorithm to slow down as your images get bigger, especially if they are about the size or bigger than your GPU memory.

**Comment by JLiLab** [comment]
What I noticed was that unmixing could not remove bleed-through signals when the image reached a certain size. But it worked after I downsized the image. We would hope that the algorithm should produce a similar unmixed image regardless of the image size and computer hardware, right?

By the way, with my Mac without a GPC, I used:
ims_ = np.array([sink_im.flatten(), source_im.flatten()]).T
mixing_parameters = model.mixing_parameters
alpha = mixing_parameters[0,:]
bg = mixing_parameters[1,:].T
# Unmix images
unmixed_im = (ims_ - bg).clip(min=0).dot(alpha)
unmixed_im = unmixed_im.clip(min=0).astype('uint16')
unmixed_sink = unmixed_im[:,0].reshape((sink_im[:,:].shape)).squeeze()

It gave the following error message that I mentioned before when I tried:
unmixed_sink = model.unmix_images([sink_im, source_im])

**Comment by JLiLab** [comment]
I forgot to mention that I found the same phenomenon when I used the PICASSO plugin in Napari interactively.
